name: Install C++, Rust, and Zig

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  setup-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v4

      - name: Install C++ (GCC and G++)
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Zig (via official release)
        run: |
          ZIG_VERSION=$(curl -s https://ziglang.org/download/index.json | jq -r '.["master"]["version"]')
          ZIG_URL=$(curl -s https://ziglang.org/download/index.json | jq -r '.["master"]["linux"]["x86_64"]["tarball"]')
          curl -LO "$ZIG_URL"
          tar -xf zig-linux-x86_64-*.tar.xz
          ZIG_DIR=$(find . -maxdepth 1 -type d -name "zig-linux-x86_64-*")
          echo "$PWD/$ZIG_DIR" >> $GITHUB_PATH
          echo "Zig installed at $PWD/$ZIG_DIR"
